/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTD3 (number 96), D12
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITENET_D12_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITENET_D12_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITENET_D12_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITENET_D12_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITENET_D12_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC12 (number 84), D8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITENET_D8_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITENET_D8_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITENET_D8_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITENET_D8_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITENET_D8_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC3 (number 73), D7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITENET_D7_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITENET_D7_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITENET_D7_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITENET_D7_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITENET_D7_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTB23 (number 69), D4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITENET_D4_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITENET_D4_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITENET_D4_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITENET_D4_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITENET_D4_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTA4 (number 38), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITENET_SW3_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITENET_SW3_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITENET_SW3_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITENET_SW3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITENET_SW3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features for the Ethernet.
 *
 */
void BOARD_InitENET(void);

/*! @name PORTE26 (number 33), LED_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_GREEN_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define LED_GREEN_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_GREEN_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define LED_GREEN_PIN 26U                   /*!<@brief PORT pin number */
#define LED_GREEN_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTB21 (number 67), LED_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_BLUE_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define LED_BLUE_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_BLUE_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define LED_BLUE_PIN 21U                   /*!<@brief PORT pin number */
#define LED_BLUE_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTB22 (number 68), LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_RED_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define LED_RED_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_RED_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define LED_RED_PIN 22U                   /*!<@brief PORT pin number */
#define LED_RED_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features for the LEDs.
 *
 */
void BOARD_InitLEDs(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*!
 * @brief Configures pin routing and optionally pin electrical features for serial comm.
 *
 */
void BOARD_InitSerial(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features for PWM.
 *
 */
void BOARD_InitPWM(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
